#!/usr/bin/env bash
# Conventional Commits validation. Usage: check-commit-msg.sh <path-to-COMMIT_EDITMSG>
set -euo pipefail

msg_file="$1"
# First non-empty, non-comment line.
subject="$(grep -v '^#' "$msg_file" | sed '/^[[:space:]]*$/d' | head -n1)"

# Merge and revert commits are generated by git and exempt.
case "$subject" in
  "Merge "*|"Revert "*) exit 0 ;;
esac

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._-]+\))?!?: .+'

if ! printf '%s' "$subject" | grep -qE "$pattern"; then
  cat >&2 <<EOF
error: commit message does not follow Conventional Commits.

  got:      $subject
  expected: <type>[optional scope]: <description>
  example:  feat(home): add pull to refresh

  types: feat fix docs style refactor perf test build ci chore revert
EOF
  exit 1
fi

if [ "${#subject}" -gt 72 ]; then
  echo "error: commit subject is ${#subject} characters, limit is 72." >&2
  exit 1
fi
